### ISSUE TITLE
"Searching with regular expressions" in "Counting and Mining" and its flags

### ISSUE THREAD

**Issue by andreaswalker** [LibraryCarpentry/lc-shell#118]
The exercise "Searching with regular expressions" in "Counting and Mining with the Shell" and its proposed solution could probably use some re-wording: If the file created is to only contain the found ISSNs, the command already requires the -o flag (which is only pointed out in the exercise below). Also, the -E flag version fails rather silently (i.e. simply doesn't produce any result, rather than giving an error message) on my system (Ubuntu). When redirecting output to a file immediately, this can easily be missed, so maybe learners should be encouraged to check the results in some way. It could be helpful to also include the (clumsy, but -E/P-less) version of 

`grep -o '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]' 2014-01_JA.tsv`

**Comment by alex-ball** [comment]
In fairness, the exercise "Searching with regular expressions" does explicitly point out that you might need `-P` instead of `-E` (in order for the bare `{` characters to be treated specially). Some would take that as a prompt to check, but yes, as there is no feedback when the pattern doesn't match, it might be best to include a reminder to look at the answer with `less`.

The greater problem lies in the exercise "Finding unique values", where the issue is ignored. I'd suggest including a parallel `-P` solution and again include a prompt to check the output.
