### ISSUE TITLE
email submission: suggest adding Hello World

### ISSUE THREAD

**Issue by karenword** [LibraryCarpentry/lc-shell#143]
Submitted via email Aug 4, 2020:

"I checked the training material of all carpentries and I was wondering
why there is no "Hello World" example in all fields available. In
general, when I started programming in different languages and with the
command line, there was always in the beginning an example including
something with "Hello World", e.g. for Unix

echo Hello World

was my first command in the shell. Learners that have started in the
field will appreciate "Hello World" examples, because they can
understand and compare such common examples if they are interest in more
programming languages. Therefore I suggest to add "echo Hello World" for
example as first command for the Unix part in the Library Carpentry."

**Comment by jmjamison** [comment]
Good point. That's a tradition for many of us who have taken programming classes. (Mine go back to IBM 370 Assembly and Pascal) However many of the people taking the Library Carpentry Intro to Shell class aren't programmers or familiar with the tradition. "Hello World" would fit more comfortably with an intro to programming workshop, especially Python rather than here.   But thank you for the suggestion.

**Comment by jmjamison** [comment]
Good point. That's a tradition for many of us who have taken programming classes. (Mine go back to IBM 370 Assembly and Pascal) However many of the people taking the Library Carpentry Intro to Shell class aren't programmers or familiar with the tradition. "Hello World" would fit more comfortably with an intro to programming workshop, especially Python rather than here. But thank you for the suggestion.
