### ISSUE TITLE
Include instructions to switch to Bash for recent MacOS versions

### ISSUE THREAD

**Issue by tobyhodges** [LibraryCarpentry/lc-shell#202]
Recent versions of MacOS (since Mojave, I think?) use Zsh as the default shell instead of Bash. The setup instructions for this lesson mention this but do not provide instructions for how a learner can make sure they are using Bash to follow the lesson. If they do not switch over, it is likely they will not notice any problem for the first parts of the lesson, but will run into trouble unexpectedly in later episodes, e.g. when they need to start writing loops. 

Switching over to Bash to follow this lesson is relatively easy - run the `bash` command in the terminal - but the lesson setup instructions should be updated to include that step. For an example, see the 'MacOS' tab of [the 'Open a new shell' instructions from the Software Carpentry Shell Novice lesson](https://swcarpentry.github.io/shell-novice/setup.html#open-a-new-shell).

**Comment by GJHausman** [comment]
A further point regarding zsh: since several additional MacOS versions have been released since Catalina (Big Sur, Monterey, and Ventura) the text in Terminal Setup: Mac OS should be modified to reflect this. Perhaps rewrite "Zsh is the default in Catalina" to read "Zsh is the default starting with Catalina"

**Comment by ndporter** [comment]
Given most people are no longer running Catalina, this should probably be updated sooner rather than later.

An alternative to giving directions to switch to Bash is simple to note that Bash and Zsh work basically identically for the material in the lesson, but do have some differences. I've taught this lesson with both and not noticed any issues except slight differences in display.
