### ISSUE TITLE
Missing file in the shell lesson zip?

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-shell#43]
I just used https://github.com/LibraryCarpentry/lc-shell/raw/gh-pages/data/shell-lesson.zip for a recent workshop and noticed that the Little Women file is missing. @jt14den or anyone else, do you have the file and can you add it to the zip file?

**Comment by katrinleinweber** [comment]
Fixed in 086f1dbf16910e8a6dbe7f2f53aaf7f85ed716f0. Thanks!

@jt14den: You can use [GitHub's closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to auto-close issues that you address with a commit ;-)

**Comment by katrinleinweber** [comment]
Please reopen. I read further in the lesson, and found [the download instructions](https://github.com/LibraryCarpentry/lc-shell/blame/da00f5edbcd4ea7548c3c903f5720f5e29b11128/_episodes/05-counting-mining.md#L738). That's probably why the file was not included (intentionally).

However, because [PG blocks Germany](https://cand.pglaf.org/germany/), it's good that the file is included here now :-)

However:

- [ ] that instruction section should be updated to reflect the file's inclusion, but
- [ ] [PG should still be mentioned appropriately](https://github.com/LibraryCarpentry/lc-shell/search?q=%22gutenberg%22&unscoped_q=%22gutenberg%22)

**Comment by libcce** [comment]
Thanks for catching this @katrinleinweber !

**Comment by libcce** [comment]
I can't assign this to you yet @katrinleinweber. I made you a collaborator which should allow me to assign it to you once you have accepted.

**Comment by jt14den** [comment]
We should change that paragraph instead & it's better to keep in the zip per my experience teaching it. I can work on it.
