### ISSUE TITLE
Change cd to pwd w/ description in setup

### ISSUE THREAD

**Issue by libcce** [LibraryCarpentry/lc-shell#57]
Recommend pwd instead of cd to test/demo that everything is working and provide a brief description: The output will be a path to your home directory.

In https://librarycarpentry.org/lc-shell/setup.html

**Comment by katrinleinweber** [comment]
IMHO, that lone `cd` is intended to ensure that all learners start the lesson in their home directory, not so much to test the shell itself, or the download of the lesson files.

What advantage would using `pwd` instead provide?

If `cd` should be changes there (I don't think it has to), I would suggest to add `cd Desktop/shell-lesson` right after `cd`, because this sets the stage for https://github.com/LibraryCarpentry/lc-shell/blame/bac0ead35c8ab475c16d2f0d9a59286ff721c88b/_episodes/02-navigating-the-filesystem.md#L107-L124

**Comment by libcce** [comment]
`cd` doesn't return a response (as new users sometimes need a response to demonstrate that something is working). `pwd` does return your current directory so at least the learner gets an initial response. With regard to Windows users, I've used `pwd` to troubleshoot initially, to get everyone setup properly. But honestly, I don't mind if it doesn't change. It was only a suggestion.

**Comment by katrinleinweber** [comment]
Ah, I get it: A response could indeed be the point here! Apologies that I didn't think of this before.
